Release/v3.0.0
BioJulia/GenomicFeatures.jl pull request #50
Opened 2023-04-20 15:43 UTC by CiaranOMara

This PR refactors `GenomicFeatures` to make use of abstract types.

This PR contains the following breaking changes.
- The `Interval` type is renamed `GenomicInterval` and now subtypes `AbstractGenomicInterval`.
- The  `IntervalCollection` is now `GenomicIntervalCollection`, and the element type of the collection is now the `AbstractGenomicInterval` instead of the interval's metadata type.
- Intervals are now grouped by the more generic `groupname` instead of `seqname`.

2023-04-21 01:51 UTC, kescobo reviewed
I'm not going to pretend I understand the scope of these changes. I can do a more detailed review if you think that would be helpful, but I trust you to make good decisions here. 

My only high-level comment is that all doctests should probably pass (or be removed) at this stage before merging. No reason to have our first post-1.0 docs be instantly outdated :wink:

2023-04-27 12:58 UTC, CiaranOMara commented
@kescobo, this PR is now ready for review again. I think I addressed your comment and tidied up a few loose ends.

2023-04-27 14:26 UTC, kescobo requested changes
I left a bunch of comments, but the vast majority amount to style preferences, and I do not feel strongly enough to consider them blocking. There is one spot where it looks like a `T` didn't get correctly changed to `I` (or vice versa), but that's the only part of this review that I would insist on.

The big style ones that show up in a few places look as if you were copying the previous style, but I think should be changed are

1. A bunch of block that have the struture `if ... return X; end; if ... return Y; end; return Z` that I think should either be `if/elseif/else`, or else use short-circuiting `&& return X`
2. A bunch of function definitions that are are just returning something that I think could be written with `foo() = X` rather than `function foo(); return X; end`

In both cases, I commented on one or two examples, but there were many more that I didn't flag. If you do want to make these changes but don't want to put in the extra tedious effort, I can do them as a separate PR - neither of them should change the functionality, so they can safely be done after v3.0 is tagged.

2023-04-27 14:27 UTC, kescobo commented on src/GenomicFeatures.jl
> +end
@CiaranOMara This is the one thing that I think *needs* a change. Everything else is style, I think

2023-04-28 02:36 UTC, CiaranOMara commented on src/GenomicFeatures.jl
> +end
That definitely needs to change. That it got this far undetected definitely reinforces a need for test coverage. I've added tests to the commit in which it was introduced.

2023-04-28 02:36 UTC, CiaranOMara commented on src/GenomicFeatures.jl
> +    return T
My preference is to use the verbose function block because I've found IDE hyperclicks unreliable or slower than a global search.

2023-04-28 03:15 UTC, CiaranOMara commented on src/coverage.jl
> +function coverage_process_lasts_heap!(cov::GenomicIntervalCollection{GenomicInterval{UInt32}}, current_coverage, coverage_groupname, coverage_first, lasts)
Not sure. This use of `UInt32` was a historic choice made by either @bicycle1885 or @SabrinaJaye. We can loosen the type requirement after this is merged and check the benchmarks.

2023-04-28 03:42 UTC, CiaranOMara commented on src/interval.jl
> +    if (rightposition(a) < leftposition(b) && groupname(a) == groupname(b))
You're correct. Parentheses removed.

2023-04-28 14:05 UTC, kescobo commented on src/GenomicFeatures.jl
> +    return T
OK, 100% your call

2023-04-28 14:06 UTC, kescobo submitted a review, later dismissed

2023-05-01 00:40 UTC, CiaranOMara commented
Thanks @kescobo.

2023-05-01 00:48 UTC, merged